[build]
  publish = "."
  functions = "netlify/functions"

[[scheduled-functions]]
  name = "scraper"
  schedule = "0 */6 * * *"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
